export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN= 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR= 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN= 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS= 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR= 'LOGIN_USER_ERROR'

export const LOGOUT_USER= 'LOGOUT_USER'

export const CREATE_COMPANY_BEGIN = 'CREATE_COMPANY_BEGIN'
export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'
export const CREATE_COMPANY_ERROR = 'CREATE_COMPANY_ERROR'

export const CREATE_PRODUCT_BEGIN = 'CREATE_PRODUCT_BEGIN'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'